version: 2
project_name: teldrive-mcp

before:
  hooks:
    - go generate

builds:
  - env:
      - CGO_ENABLED=0
    main: main.go
    flags: -trimpath
    ldflags:
      - -extldflags=-static
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

archives:
  - name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - README*.md
      - LICENSE

dockers:
  - image_templates:
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-amd64"
    use: buildx
    dockerfile: goreleaser.dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-arm64"
    use: buildx
    dockerfile: goreleaser.dockerfile
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/tgdrive/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-arm64"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Refactoring
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 3
  filters:
    exclude:
      - "^README"
      - "^Update"
      - "^Version"
      - "^ci:"
      - "^docs:"
      - Merge pull request
      - Merge branch

release:
  draft: true
