generator:
  features:
    disable:
      - "ogen/otel"
      - "paths/server"
      - "client/request/validation"
      - "webhooks/server"
      - "webhooks/client"
      - "ogen/unimplemented"
      - "debug/example_tests"
  convenient_errors: "on"